#db_path: "./runtime.db"
#symbol: "1306.T"          # ←ここだけ必須
#
## 以下は好み。ETFはボラ低めなので最初は±0.5あたりが当たりやすい
#thr_long: 0.5
#thr_short: -0.5
#exit_long: -0.1
#exit_short: 0.1
#ttl_min: 8
#lot_size: 100
#fee_rate: 0.0002
## ↓この4つは現行の ingest/strategy では使っていないので残してOK（影響なし）
#jst_start: "09:00"
#jst_end: "10:00"
#ingest_period: "7d"
#use_yfinance: true
db_path: "./runtime.db"
symbol: "7203.T"          # ←ここだけ 7203.T に戻す
jst_start: "09:00"
jst_end: "10:00"


# しきい値（まずはロングだけ刺さるように）
thr_long: 0.1        # ← sampleが出した p70≈0.249 を少し下回らせる
thr_short: -0.50      # ← ショートは当面オフに近い値に
ema_span: 3
confirm_bars: 1

# ゲートは切り分けのため一旦OFF
min_edge: 0.0
min_slope: 0.0
vwap_gate: false

# 9:00-10:00そのまま、サブ時間帯は使わない
sub_start: null
sub_end: null

# 約定出しやすく
max_trades_per_day: 10
# 片側だけにしたいなら（任意）
# side_filter: "long"
auto_thresholds: false     # or
thr_mode: "fixed"

# config.toyota.yaml
db_path: ./runtime.db
symbol: 7203.T
jst_start: "09:00"
jst_end: "10:00"

weights:
  pack1: 1.0
  pack2: 1.0
  pack3: 0.5
  pack4: 0.5
  pack5: 0.0
  pack6: 0.0
  pack7: 0.0
  pack8: 0.0
  pack9: 0.0
  pack10: 0.0
