# トレード戦略設定（Toyota用）
symbol: "7203.T"

# エントリー／クローズ閾値
thr_long: 0.15       # ロング閾値を少し厳しく
thr_short: -0.5
exit_long: 0.05      # クローズは少し緩めに
exit_short: -0.1

# 判定条件
confirm_bars: 2      # 2本連続で閾値を超えてから入る
min_edge: 0.02       # 閾値より0.02余裕を持たせる
min_slope: 0.0       # 傾き条件は今回はOFF

# EMA平滑
ema_span: 3

# その他ゲート
cooldown_bars: 0
vwap_gate: false
side_filter: both

# リスク管理
max_trades_per_day: 50
ttl_min: 8
lot_size: 100
fee_rate: 0.001
