"20250922_1":
  thr_long: 0.10
  thr_short: -0.50
  exit_long: 0.10
  exit_short: -0.10
  confirm_bars: 1
  min_edge: 0.0
  min_slope: 0.0

"20250922_2":
  thr_long: 0.15
  thr_short: -0.50
  exit_long: 0.05
  exit_short: -0.10
  confirm_bars: 2
  min_edge: 0.02
  min_slope: 0.0

"20250921_2":
  thr_long: 0.12
  thr_short: -0.50
  exit_long: 0.03
  exit_short: -0.10
  confirm_bars: 2
  min_edge: 0.0
  min_slope: 0.0
